apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-06T09:07:11Z"
  generation: 1
  labels:
    app: maven-app
  name: maven-app
  namespace: default
  resourceVersion: "116803"
  uid: e87de889-d602-45dd-957a-38ddd20bc83f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maven-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven-app
    spec:
      containers:
      - image: asnashameel/maven-app:latest
        imagePullPolicy: Always
        name: maven-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-06T09:07:11Z"
    lastUpdateTime: "2025-04-06T09:07:41Z"
    message: ReplicaSet "maven-app-6c94b668c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-06T09:34:01Z"
    lastUpdateTime: "2025-04-06T09:34:01Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
